### ISSUE TITLE
what

### ISSUE THREAD

**Issue by SixThreeNineTwo** [Discord-Theme-Addons/discord-name-badges#39]
Username and Discrim: 6392
User ID: 692206224745431161
Image Link: https://giantbomb1.cbsistatic.com/uploads/square_tiny/2/26644/853759-cirno.jpg

**Comment by LuckFire** [comment]
if you can provide me an image link from a trusted domain ill add it (i dunno i that domain is trusted or not)
pls read https://github.com/Discord-Theme-Addons/NameBadges#badge-request

**Comment by HooferDevelops** [comment]
added, changed the image link to a discord cdn.

**Comment by LuckFire** [comment]
thank u hooFyFYFYfy
