### ISSUE TITLE
Badge Change

### ISSUE THREAD

**Issue by LilKurisuu** [Discord-Theme-Addons/discord-name-badges#49]
Username and Discrim: **wholesome kris (0001)**
User ID: 330544247042473984
Image Link: https://i.pxl.blue/em3ed4A44.gif

**Comment by LuckFire** [comment]
please upload it to a different image host

**Comment by LilKurisuu** [comment]
heres the new link

Image Link: https://media.discordapp.net/attachments/778759746798485518/819646292070236160/em3ed4A44.gif

**Comment by LuckFire** [comment]
![image](https://user-images.githubusercontent.com/39076891/110841367-ca312380-8273-11eb-807c-cca6450c7731.png)
it looks kind of off, do you have a different one in mind?

**Comment by LilKurisuu** [comment]
what about this one?
https://media.discordapp.net/attachments/778759746798485518/819650718058283008/tenor.gif

**Comment by LuckFire** [comment]
![image](https://user-images.githubusercontent.com/39076891/110842426-129d1100-8275-11eb-89b3-466776a8f059.png)
looks fine

**Comment by LuckFire** [comment]
done~
