### ISSUE TITLE
BADGE REQUEST arctic#9999

### ISSUE THREAD

**Issue by CodingArctic** [Discord-Theme-Addons/discord-name-badges#55]
**What is your Discord Tag?**
arctic#9999

**What is your UID (User ID)?**
160504751203549185

**What is the image for the badge that you want?**
Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.
https://media.tenor.com/images/054e7e7f6060bf2fcdb72634b926ee29/tenor.gif

**Comment by LuckFire** [comment]
done~
