### ISSUE TITLE
BADGE REQUEST [CloneyInnit#6510]

### ISSUE THREAD

**Issue by CloneyInnit** [Discord-Theme-Addons/discord-name-badges#56]
**What is your Discord Tag?**
CloneyInnit#6510

**What is your UID (User ID)?**
729934422068953098

**What is the image for the badge that you want?**
Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.com
https://cdn.discordapp.com/attachments/818142332641607712/820685833057075260/partner.png

**Comment by LuckFire** [comment]
done~
