### ISSUE TITLE
BADGE REQUEST mugman#5453

### ISSUE THREAD

**Issue by mugman174** [Discord-Theme-Addons/discord-name-badges#57]
**What is your Discord Tag?**
mugman#5453

**What is your UID (User ID)?**
601836455006044163

**What is the image for the badge that you want?**
https://media.discordapp.net/attachments/820752295246430268/821415788296667136/banner.png
![banner.png](https://media.discordapp.net/attachments/820752295246430268/821415788296667136/banner.png)

**Comment by dnglchlk** [comment]
just a helpful pointer, this image that you're choosing should probably be square, and is a little tiny thing on your screen, idk if you know this

**Comment by LuckFire** [comment]
^ what was said above, this image would probably not look how you want it
i can either use this one or you can choose a different one

**Comment by LuckFire** [comment]
done~
