### ISSUE TITLE
BADGE REQUEST [snuuy#7976]

### ISSUE THREAD

**Issue by IRLSNUUY** [Discord-Theme-Addons/discord-name-badges#61]
**What is your Discord Tag?**
snuuy#7976

**What is your UID (User ID)?**
600813915030421504

**What is the image for the badge that you want?**
Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.

https://cdn.discordapp.com/attachments/792133428161675346/822272749891223562/50a3e3178733e88.png

**Comment by LuckFire** [comment]
done~
