### ISSUE TITLE
UPDATE BADGE REQUEST [USERNAME#0001]

### ISSUE THREAD

**Issue by Laurino108** [Discord-Theme-Addons/discord-name-badges#63]
**What is your Discord Tag?**
Laurino108#9563

**What is your UID (User ID)?**
433698489462161408

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/YQyZwow.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
updated!
