### ISSUE TITLE
BADGE REQUEST [kckarnige#0266]

### ISSUE THREAD

**Issue by kckarnige** [Discord-Theme-Addons/discord-name-badges#64]
**What is your Discord Tag?**
_kckarnige#0266_

**What is your UID (User ID)?**
_634168893644210186_

**What is the image for the badge that you want?**
_https://cdn.discordapp.com/attachments/734047180045811773/823170108682666004/favicon.png_

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comments**
_Here's some choccy milk, because you're epic :D_
![image](https://user-images.githubusercontent.com/32397453/111904809-1839ea00-8a1f-11eb-9dea-07f0b36a8825.png)

**Comment by LuckFire** [comment]
done and ty for the choccy milk :D

**Comment by kckarnige** [comment]
And think you for the badge :3
