### ISSUE TITLE
UPDATE BADGE REQUEST [Dormy#8393]

### ISSUE THREAD

**Issue by Carbonixx** [Discord-Theme-Addons/discord-name-badges#65]
**What is your Discord Tag?**
Dormy#8393

**What is your UID (User ID)?**
319029124666490881

What is the image for the badge that you want?

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/fV1gLat.gif

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
updated!
