### ISSUE TITLE
BADGE REQUEST [C4rn1ge [BETA]#2382] (For a bot)

### ISSUE THREAD

**Issue by kckarnige** [Discord-Theme-Addons/discord-name-badges#66]
**What is your Discord Tag?**
C4rn1ge [BETA]#2382

**What is your UID (User ID)?**
717479391130681453

**What is the image for the badge that you want?**
https://cdn.discordapp.com/attachments/734047180045811773/823495788712951808/c41.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comments:**
This badge is for a bot I'm working on :3 (I think I put too much effort into this meme xD)

![Shit, it didn't load ;w;"](https://user-images.githubusercontent.com/32397453/112001217-22c6b300-8af5-11eb-8fe7-4099168eb70c.png)

**Comment by LuckFire** [comment]
done any ty for the milk :>
