### ISSUE TITLE
BADGE REQUEST [bwee#1337]

### ISSUE THREAD

**Issue by bweeirl** [Discord-Theme-Addons/discord-name-badges#67]
**What is your Discord Tag?**
bwee#1337

**What is your UID (User ID)?**
274909326869528576

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/W4JaT6u.png
**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done~
