### ISSUE TITLE
BADGE REQUEST [aokiare#0666]

### ISSUE THREAD

**Issue by Aokiare** [Discord-Theme-Addons/discord-name-badges#68]
**What is your Discord Tag?**
`aokiare#0666`

**What is your UID (User ID)?**
336678828233588736

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/gxZM0Fg.gif

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done~
