### ISSUE TITLE
BADGE REQUEST [SamyoFox#5527]

### ISSUE THREAD

**Issue by Samyocord** [Discord-Theme-Addons/discord-name-badges#71]
**What is your Discord Tag?**
SamyoFox#5527

**What is your UID (User ID)?**
121987758674673664

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/DEcVi4W.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
