### ISSUE TITLE
BADGE REQUEST [novo#7267]

### ISSUE THREAD

**Issue by novotab51** [Discord-Theme-Addons/discord-name-badges#72]
**What is your Discord Tag?**
novo#7267

**What is your UID (User ID)?**
537316892038266900

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.ibb.co/7kmXLpN/androidthemes-nobg.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by Samyocord** [comment]
NovoBADGE badge

**Comment by LuckFire** [comment]
done
