### ISSUE TITLE
UPDATE BADGE REQUEST [kckarnige#0266]

### ISSUE THREAD

**Issue by kckarnige** [Discord-Theme-Addons/discord-name-badges#73]
**What is your Discord Tag?**
`kckarnige#0266`

**What is your UID (User ID)?**
`634168893644210186`

**What is the image for the badge that you want?**
https://kckarnige.github.io/res/discord-name-badge.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comments**
I just realized the form said "trusted domains", and that I'm not only restricted to Discord CDN links and Imgur :p
I want it to be this image URL so I won't have to bother you about updating it, I could do it instead :3

**Comment by LuckFire** [comment]
done~

also that's a pretty smart idea!
