### ISSUE TITLE
BADGE REQUEST [Orangemn6#9427]

### ISSUE THREAD

**Issue by orangemn6** [Discord-Theme-Addons/discord-name-badges#74]
**What is your Discord Tag?**
Orangemn6#9427

**What is your UID (User ID)?**
755856191959334932

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***

https://cdn.discordapp.com/attachments/809209611676024894/824833255680507944/web.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
