### ISSUE TITLE
BADGE REQUEST [ ༄Samomen#1231]

### ISSUE THREAD

**Issue by GodSamomen** [Discord-Theme-Addons/discord-name-badges#75]
**What is your Discord Tag?**
༄Samomen#1231

**What is your UID (User ID)?**
711325368333893722

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
       https://cdn.discordapp.com/emojis/635936642372337674.png?v=1
**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
