### ISSUE TITLE
BADGE REQUEST [ItzXenonUnity | Lou#2369]

### ISSUE THREAD

**Issue by XenonUnity** [Discord-Theme-Addons/discord-name-badges#76]
**What is your Discord Tag?**
ItzXenonUnity | Lou#2369

**What is your UID (User ID)?**
701850907893301328

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/emojis/781266154218979368.png?v=1

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done!
