### ISSUE TITLE
UPDATE BADGE REQUEST [AHIRA#1216]

### ISSUE THREAD

**Issue by AHIRAISSHY** [Discord-Theme-Addons/discord-name-badges#79]
**What is your Discord Tag?**
AHIRA#1216

**What is your UID (User ID)?**
249521750465970177

**What is the image for the badge that you want?
https://cdn.discordapp.com/emojis/826225302887858249.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done!
