### ISSUE TITLE
BADGE REQUEST [USERNAME#0001]

### ISSUE THREAD

**Issue by Kuro-png** [Discord-Theme-Addons/discord-name-badges#80]
**What is your Discord Tag?**
Maddox#5145

**What is your UID (User ID)?**
558553662910234625

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/attachments/787393127484096565/826529184800964618/pokemon_ultra_moon_icon_by_luismgalindo_dbswcgb-fullview.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done! sorry it took so long lol
