### ISSUE TITLE
UPDATE BADGE REQUEST [DFA R0dn3yS#2244]

### ISSUE THREAD

**Issue by R0dn3yS** [Discord-Theme-Addons/discord-name-badges#81]
**What is your Discord Tag?**
DFA R0dn3yS 2244

**What is your UID (User ID)?**
325254775828512778

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/M4NrT4r.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done! sorry it took so long lol
