### ISSUE TITLE
BADGE REQUEST [jewdev#8485]

### ISSUE THREAD

**Issue by jewdev** [Discord-Theme-Addons/discord-name-badges#83]
**What is your Discord Tag?**
jewdev#8485

**What is your UID (User ID)?**
222369866529636353

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/1EI78Ux.gif

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
