### ISSUE TITLE
BADGE REQUEST [Maroxy#4964]

### ISSUE THREAD

**Issue by Mar0xy** [Discord-Theme-Addons/discord-name-badges#84]
**What is your Discord Tag?**
Maroxy#4964

**What is your UID (User ID)?**
82662823523516416

**What is the image for the badge that you want?**
https://i.imgur.com/2oxNPUW.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
