### ISSUE TITLE
BADGE REQUEST [Ritzy#1608]

### ISSUE THREAD

**Issue by RitzyVex** [Discord-Theme-Addons/discord-name-badges#86]
**What is your Discord Tag?**
Ritzy#1608

**What is your UID (User ID)?**
505432621086670872

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/VfBA8MF.jpg

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
