### ISSUE TITLE
BADGE REQUEST [ekto#4153]

### ISSUE THREAD

**Issue by ekto** [Discord-Theme-Addons/discord-name-badges#87]
**What is your Discord Tag?**
ekto#4153

**What is your UID (User ID)?**
447353865122086932

**What is the image for the badge that you want?**
https://media.discordapp.net/attachments/832737284947181649/833861089547780116/image.png
**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done

**Comment by ekto** [comment]
Thank you for your hard work
