### ISSUE TITLE
BADGE REQUEST [Crenshaw#1312]

### ISSUE THREAD

**Issue by Crenshaw1312** [Discord-Theme-Addons/discord-name-badges#88]
**What is your Discord Tag?**
Crenshaw#1312

**What is your UID (User ID)?**
766385575530856458

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/emojis/673441482690134016.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
