### ISSUE TITLE
BADGE REQUEST [Kuhmann#1107]

### ISSUE THREAD

**Issue by jescowalker** [Discord-Theme-Addons/discord-name-badges#89]
**What is your Discord Tag?**
Kuhmann#1107

**What is your UID (User ID)?**
519698069340684298

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://i.imgur.com/rs8IzK1.gif

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
