### ISSUE TITLE
BADGE REQUEST [EnliX ♡#3991]

### ISSUE THREAD

**Issue by Enlixe** [Discord-Theme-Addons/discord-name-badges#90]
**What is your Discord Tag?**
EnliX ♡#3991

**What is your UID (User ID)?**
524805915526955048

**What is the image for the badge that you want? *Please make sure that the image is hosted on a trusted domain, such as i.imgur or cdn.discordapp.***
https://cdn.discordapp.com/attachments/781506453492072469/826265187828760626/angelvulpix_808999506048974869.png

**Additional Confirmation:** 
- [x] My badge does not contain any NSFW material. 
- [x] My badge is not a badge that signifies that I am an official developer / staff for Discord or client mod communities.

**Comment by LuckFire** [comment]
done
